project:
  type: website
  output-dir: docs

website:
  title: "Omar Lizardo"
  search: true
  repo-url: https://github.com/olizardo/mysite
  repo-actions: [source]
  navbar:
    background: "#2D68C4"
    right:
      - file: pubs.qmd
        text: "Work"
        icon: pencil-square
      - file: blog.qmd
        text: "Blog"
        icon: journal-richtext
      - text: "Teaching"
        icon: pencil
        menu: 
          - text: "Social Networks (111) Textbook"
            icon: book
            href: https://olizardo.github.io/networks-textbook/
          - text: "Classical Social Theory Lecture Notes"
            icon: book
            href: https://olizardo.github.io/classical-sociological-theory-notes/
          - text: "SOCIOL 208B (Spring 2022)"
            icon: file-text
            href: syllabi/SOCIOL208b-spring22.html
          - text: "SOCIOL 204 (Sociological Theorizing)"
            icon: file-text
            href: syllabi/SOCIOL204.html
          - text: "SOCIOL 245 (Cultural Sociology)"
            icon: file-text
            href: syllabi/SOCIOL245.html
          - text: "SOCIOL 111 (Social Networks)"
            icon: file-text
            href: syllabi/SOCIOL111.html
      - file: vita.pdf
        text: "Vita"
        icon: file-pdf
      - file: bio.qmd
        text: "Bio"
        icon: person-circle
      - href: mailto:olizardo@soc.ucla.edu
        icon: envelope
        text: "Email"
        
format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: source

