project:
  type: website
  output-dir: docs

website:
  title: "Omar Lizardo's Academic Website"
  search: true
  open-graph: true
  repo-url: https://github.com/olizardo/mysite
  repo-actions: [source]
  navbar:
    background: "#2D68C4"
    right:
      - file: pubs.qmd
        text: "Work"
        icon: pencil-square
      - file: blog.qmd
        text: "Blog"
        icon: journal-richtext
      - text: "Teaching"
        icon: pencil
        menu: 
          - text: "Social Networks (111) Textbook"
            icon: book
            href: https://olizardo.github.io/networks-textbook/
          - text: "SOCIOL 111 (Social Networks Undergraduate Class)"
            icon: file-text
            href: syllabi/SOCIOL111.qmd
          - text: "SOCIOL 204 (Topics in Sociological Theorizing)"
            icon: file-text
            href: syllabi/SOCIOL204.qmd
          - text: "Computational Networks Sequence (208A & 208B)"
            icon: file-text
            href: https://olizardo.github.io/SOCIOL208/
          - text: "SOCIOL 245 (Cultural Sociology)"
            icon: file-text
            href: syllabi/SOCIOL245.qmd

      - file: vita.pdf
        text: "Vita"
        icon: file-pdf
      - file: bio.qmd
        text: "Bio"
        icon: person-circle
      - href: mailto:olizardo@soc.ucla.edu
        icon: envelope
        text: "Email"
        
format:
  html:
    theme:
      light: flatly
      dark: darkly    
    css: styles.css
    toc: true
    linkcolor: "#ff7e26;"

editor: source

