---
title: "Brief Biographical Notes"
---

### Early Life

I was born in New York City, spent the better part of the first 17 years of my life in a (then) small coastal city called [La Romana](https://en.wikipedia.org/wiki/La_Romana,_Dominican_Republic) (i.e. "The Roman" with feminine inflection) on the Southeast corner of Dominican Republic, and have lived in the U.S. ever since.

### Academic Training

I earned a Bachelor of Science in Psychology from Brooklyn College in 1997. Starting in the year 2000, I enrolled in the graduate program in the [Department of Sociology at the University of Arizona](https://sociology.arizona.edu/), where I was fortunate to earn a Ph.D. in 2006 under the supervision and mentorship of [Ron Breiger](https://profiles.arizona.edu/person/breiger) and [Al Bergesen](https://en.wikipedia.org/wiki/Albert_Bergesen).

### Early Academic Career

Starting in 2006, I had the privilege to spend the first twelve years of my academic career in the [Department of Sociology at the University of Notre Dame](https://sociology.nd.edu/). I was promoted to Associate Professor with tenure in 2012, and to Full Professor in 2016. While at Notre Dame, I was selected as co-editor, with Rory McVeigh and Sarah Mustillo, of the [*American Sociological Review*](https://journals.sagepub.com/home/asr), the flagship journal of the [American Sociological Association](https://www.asanet.org/) (ASA), for a five-year term starting in 2015. In 2014, received the [Lewis Coser Award for Theoretical Agenda Setting](http://www.asatheory.org/coser-award.html) from the ASA's Section on Theory.

### Recent Academic Career

In 2018, I decided to make the transition to the West (best) coast and moved to California, where I am currently a ladder faculty member and LeRoy Neiman Term Chair Professor in the [Department of Sociology at UCLA](https://soc.ucla.edu/). While at UCLA, I was elected a member of the [Sociological Research Association](https://www.sociological-research-assoc.org/) in 2019. In 2020, I was appointed to the Board of Review Editors for the journal [Science](https://www.science.org/).
