---
title: "Bonacich Centrality and the Method of Reflections"
author: "Omar Lizardo"
date: "2024-05-05"
categories: [reflections, two-mode networks, centrality, eigenvectors]
draft: false
---




In a [previous post](https://olizardo.github.io/mysite/posts/two-mode-reflections/), I showed how the "method of reflections" introduced by Hidalgo & Hausmann (2009)---hereafter HH---works in the case of two-mode network data. While reading that, some of you might have thought that there is a well-established network centrality metric for two-mode networks that is supposed to work just like the method of reflections: That is, defining the centrality of entities in one mode (e.g., persons) according to centralities of the entities in the other mode (e.g., groups). I refer to the Bonacich "eigenvector" centrality---see Bonacich (1991) and Faust (1997) for discussion.


::: {#tbl-sw .cell tbl-cap='Southern Women Data.'}
::: {.cell-output-display}
`````{=html}
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> E1 </th>
   <th style="text-align:center;"> E2 </th>
   <th style="text-align:center;"> E3 </th>
   <th style="text-align:center;"> E4 </th>
   <th style="text-align:center;"> E5 </th>
   <th style="text-align:center;"> E6 </th>
   <th style="text-align:center;"> E7 </th>
   <th style="text-align:center;"> E8 </th>
   <th style="text-align:center;"> E9 </th>
   <th style="text-align:center;"> E10 </th>
   <th style="text-align:center;"> E11 </th>
   <th style="text-align:center;"> E12 </th>
   <th style="text-align:center;"> E13 </th>
   <th style="text-align:center;"> E14 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> BRENDA </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> CHARLOTTE </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> DOROTHY </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> ELEANOR </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> EVELYN </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> FLORA </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> FRANCES </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> HELEN </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> KATHERINE </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> LAURA </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> MYRNA </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> NORA </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> OLIVIA </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> PEARL </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> RUTH </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> SYLVIA </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> THERESA </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> VERNE </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
</tbody>
</table>

`````
:::
:::


In this post I show how the Bonacich centrality fits into the reflection idea, and why this means it is a different metric from that yielded by HH's reflection method. This also the difference between Bonacich and Correspondence Analysis (CA), because the HH reflection method is equivalent to CA. 

Consider an affiliation matrix $\mathbf{A}$ of dimensions $|P| \times |G|$ where $|P|$ is the cardinality of the person set and $|G|$ the cardinality of the group set in the two-mode network. Each entry in the matrix $a_{pg} = 1$ if person *p* affiliates with group $g$ and zero otherwise. An affiliation matrix of this type, representing Davis et al.'s (1941) famous Southern Women data, is shown as @tbl-sw. 

In this case, the degree centrality of people is given by:

$$
   C^B_p(1) = \sum_g a_{pg} 
$$ {#eq-pc}

And for groups:

$$
   C^B_g(1) = \sum_p a_{pg} 
$$ {#eq-gc}

The right hand sides of @eq-pc and @eq-gc are just the first order degree centralities of people and groups (Faust, 1997). People are central when they have many memberships and groups are central when they have many members.

Once we have this information, we can define a second order "Bonacich-reflection" on both the persons and groups using the formulas:

$$
   C^B_p(2) = \sum_g a_{pg}C^R_g(1) 
$$ {#eq-pr2}

$$
   C^B_g(2) = \sum_p a_{pg}C^R_p(1) 
$$ {#eq-gr2}

@eq-pr2 says that people are central when the sum of the number of members of the groups they belong to is large. @eq-gr2 says groups are central when the sum of the number of memberships of the people who belong to them is large. 

We can keep on going and define a third order reflection using the formulas:

$$
   C^B_p(3) = \sum_g a_{pg}C^R_g(2) 
$$ {#eq-pr3}

$$
   C^B_g(3) = \sum_p a_{pg}C^R_p(2) 
$$ {#eq-gr3}

@eq-pr3 says that people are central when the sum of the sum of the number of memberships held by the people who belong to the groups they belong to is large. @eq-pr3 says that groups are central when the sum of the sum of the number of members of the groups their members belong to is large. 

Once again, we can keep going and define fourth order, fifth order, and higher reflections $C^R_p(4), C^R_p(4) \ldots C^R_p(q)$.

More generally, the reflective Bonacich centralities for persons and groups are given by:

$$
   C^B_p(q) = \sum_g a_{pg}C^R_g(q-1) 
$$ {#eq-prq}

$$
   C^B_g(q) = \sum_p a_{pg}C^R_p(q-1) 
$$ {#eq-grq}

For all q > 1. 

Actually, the preceding set of equations won't quite work, because we are computing sums of sums, of sums which means that both the person and group reflective Bonacich centralities would diverge toward infinity as $q$ increases. 

To prevent this divergence and guarantee *convergence* to a set of manageable scores after a few iterations, we need to *normalize* the sum of centralities at each step $q > 1$ before feeding them to the subsequent sum at step $q+1$. We do this by dividing the computed centrality vectors for both persons and group at each step q by a *vector norm*, which in this case is the *Euclidean vector norm*, as follows:

$$
   C^B_p(q) = \frac{C^B_p(q)}{||C^B_p(q)||_2}
$$ {#eq-prqn}

$$
   C^B_p(q) = \frac{C^B_p(q)}{||C^B_p(q)||_2}
$$ {#eq-grqn}

With the Euclidean norm for each centrality vector defined as:

$$
   ||C^B_p(q)||_2 = \sqrt{\sum_i^{|P|}(C^B_p(q)_i)^2}
$$ {#eq-peuc}

$$
   ||C^B_g(q)||_2 = \sqrt{\sum_j^{|G|}(C^B_g(q)_j)^2}
$$ {#eq-geuc}


::: {.cell}

:::


Let's see how that looks like with real data. The results of the reflection equations for the Southern Women data, for people up to twenty reflections, are shown in @tbl-refp. The corresponding results for groups are shown in @tbl-refg. 


::: {#tbl-refp .cell tbl-cap='Bonacich reflections on Southern Women Data (Persons)'}
::: {.cell-output-display}
`````{=html}
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> 1 </th>
   <th style="text-align:center;"> 2 </th>
   <th style="text-align:center;"> 3 </th>
   <th style="text-align:center;"> 4 </th>
   <th style="text-align:center;"> 5 </th>
   <th style="text-align:center;"> 6 </th>
   <th style="text-align:center;"> 7 </th>
   <th style="text-align:center;"> 8 </th>
   <th style="text-align:center;"> 9 </th>
   <th style="text-align:center;"> 10 </th>
   <th style="text-align:center;"> 11 </th>
   <th style="text-align:center;"> 12 </th>
   <th style="text-align:center;"> 13 </th>
   <th style="text-align:center;"> 14 </th>
   <th style="text-align:center;"> 15 </th>
   <th style="text-align:center;"> 16 </th>
   <th style="text-align:center;"> 17 </th>
   <th style="text-align:center;"> 18 </th>
   <th style="text-align:center;"> 19 </th>
   <th style="text-align:center;"> 20 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> EVELYN </td>
   <td style="text-align:center;"> 0.35 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.33 </td>
   <td style="text-align:center;"> 0.33 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> LAURA </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> THERESA </td>
   <td style="text-align:center;"> 0.35 </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.37 </td>
   <td style="text-align:center;"> 0.37 </td>
   <td style="text-align:center;"> 0.37 </td>
   <td style="text-align:center;"> 0.37 </td>
   <td style="text-align:center;"> 0.37 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> BRENDA </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.31 </td>
   <td style="text-align:center;"> 0.31 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.32 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> CHARLOTTE </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> FRANCES </td>
   <td style="text-align:center;"> 0.22 </td>
   <td style="text-align:center;"> 0.23 </td>
   <td style="text-align:center;"> 0.23 </td>
   <td style="text-align:center;"> 0.24 </td>
   <td style="text-align:center;"> 0.24 </td>
   <td style="text-align:center;"> 0.24 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.25 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> ELEANOR </td>
   <td style="text-align:center;"> 0.22 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> RUTH </td>
   <td style="text-align:center;"> 0.22 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> VERNE </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.23 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.22 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> MYRNA </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> KATHERINE </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.23 </td>
   <td style="text-align:center;"> 0.22 </td>
   <td style="text-align:center;"> 0.22 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> SYLVIA </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.28 </td>
   <td style="text-align:center;"> 0.28 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> NORA </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.23 </td>
   <td style="text-align:center;"> 0.22 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> HELEN </td>
   <td style="text-align:center;"> 0.22 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> OLIVIA </td>
   <td style="text-align:center;"> 0.09 </td>
   <td style="text-align:center;"> 0.09 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> FLORA </td>
   <td style="text-align:center;"> 0.09 </td>
   <td style="text-align:center;"> 0.09 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
   <td style="text-align:center;"> 0.06 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> PEARL </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.17 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> DOROTHY </td>
   <td style="text-align:center;"> 0.09 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.13 </td>
  </tr>
</tbody>
</table>

`````
:::
:::

::: {#tbl-refg .cell tbl-cap='Bonacich reflections on Southern Women Data (Groups)'}
::: {.cell-output-display}
`````{=html}
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> 1 </th>
   <th style="text-align:center;"> 2 </th>
   <th style="text-align:center;"> 3 </th>
   <th style="text-align:center;"> 4 </th>
   <th style="text-align:center;"> 5 </th>
   <th style="text-align:center;"> 6 </th>
   <th style="text-align:center;"> 7 </th>
   <th style="text-align:center;"> 8 </th>
   <th style="text-align:center;"> 9 </th>
   <th style="text-align:center;"> 10 </th>
   <th style="text-align:center;"> 11 </th>
   <th style="text-align:center;"> 12 </th>
   <th style="text-align:center;"> 13 </th>
   <th style="text-align:center;"> 14 </th>
   <th style="text-align:center;"> 15 </th>
   <th style="text-align:center;"> 16 </th>
   <th style="text-align:center;"> 17 </th>
   <th style="text-align:center;"> 18 </th>
   <th style="text-align:center;"> 19 </th>
   <th style="text-align:center;"> 20 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E1 </td>
   <td style="text-align:center;"> 0.11 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.14 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E2 </td>
   <td style="text-align:center;"> 0.11 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.14 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E3 </td>
   <td style="text-align:center;"> 0.22 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.24 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.25 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E4 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.27 </td>
   <td style="text-align:center;"> 0.28 </td>
   <td style="text-align:center;"> 0.28 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E5 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.32 </td>
   <td style="text-align:center;"> 0.33 </td>
   <td style="text-align:center;"> 0.33 </td>
   <td style="text-align:center;"> 0.33 </td>
   <td style="text-align:center;"> 0.33 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
   <td style="text-align:center;"> 0.34 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E6 </td>
   <td style="text-align:center;"> 0.26 </td>
   <td style="text-align:center;"> 0.28 </td>
   <td style="text-align:center;"> 0.28 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.29 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
   <td style="text-align:center;"> 0.30 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E7 </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.38 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E8 </td>
   <td style="text-align:center;"> 0.51 </td>
   <td style="text-align:center;"> 0.49 </td>
   <td style="text-align:center;"> 0.51 </td>
   <td style="text-align:center;"> 0.51 </td>
   <td style="text-align:center;"> 0.51 </td>
   <td style="text-align:center;"> 0.51 </td>
   <td style="text-align:center;"> 0.51 </td>
   <td style="text-align:center;"> 0.51 </td>
   <td style="text-align:center;"> 0.51 </td>
   <td style="text-align:center;"> 0.50 </td>
   <td style="text-align:center;"> 0.50 </td>
   <td style="text-align:center;"> 0.50 </td>
   <td style="text-align:center;"> 0.50 </td>
   <td style="text-align:center;"> 0.50 </td>
   <td style="text-align:center;"> 0.50 </td>
   <td style="text-align:center;"> 0.50 </td>
   <td style="text-align:center;"> 0.50 </td>
   <td style="text-align:center;"> 0.50 </td>
   <td style="text-align:center;"> 0.50 </td>
   <td style="text-align:center;"> 0.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E9 </td>
   <td style="text-align:center;"> 0.44 </td>
   <td style="text-align:center;"> 0.37 </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.37 </td>
   <td style="text-align:center;"> 0.37 </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.36 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E10 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.16 </td>
   <td style="text-align:center;"> 0.16 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.15 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E11 </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.09 </td>
   <td style="text-align:center;"> 0.08 </td>
   <td style="text-align:center;"> 0.08 </td>
   <td style="text-align:center;"> 0.08 </td>
   <td style="text-align:center;"> 0.08 </td>
   <td style="text-align:center;"> 0.08 </td>
   <td style="text-align:center;"> 0.08 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.07 </td>
   <td style="text-align:center;"> 0.07 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E12 </td>
   <td style="text-align:center;"> 0.22 </td>
   <td style="text-align:center;"> 0.21 </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.18 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E13 </td>
   <td style="text-align:center;"> 0.11 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.11 </td>
   <td style="text-align:center;"> 0.11 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E14 </td>
   <td style="text-align:center;"> 0.11 </td>
   <td style="text-align:center;"> 0.13 </td>
   <td style="text-align:center;"> 0.11 </td>
   <td style="text-align:center;"> 0.11 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
   <td style="text-align:center;"> 0.10 </td>
  </tr>
</tbody>
</table>

`````
:::
:::


We can see that the results for both persons and groups freeze into values after a few iterations. The resulting final ranks of persons and groups are shown in @tbl-final-1 and @tbl-final-2.


::: {#tbl-final .cell layout-ncol="2" tbl-cap='Final rankings of persons and groups according to Bonacich reflections.' tbl-subcap='["Final rank of persons","Final rank of groups"]'}
::: {.cell-output-display}
`````{=html}
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> THERESA </td>
   <td style="text-align:center;"> 0.38 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> EVELYN </td>
   <td style="text-align:center;"> 0.34 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> BRENDA </td>
   <td style="text-align:center;"> 0.32 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> LAURA </td>
   <td style="text-align:center;"> 0.30 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> RUTH </td>
   <td style="text-align:center;"> 0.27 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> ELEANOR </td>
   <td style="text-align:center;"> 0.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> SYLVIA </td>
   <td style="text-align:center;"> 0.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> FRANCES </td>
   <td style="text-align:center;"> 0.25 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> VERNE </td>
   <td style="text-align:center;"> 0.21 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> KATHERINE </td>
   <td style="text-align:center;"> 0.20 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> CHARLOTTE </td>
   <td style="text-align:center;"> 0.19 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> NORA </td>
   <td style="text-align:center;"> 0.19 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> HELEN </td>
   <td style="text-align:center;"> 0.19 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> MYRNA </td>
   <td style="text-align:center;"> 0.17 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> PEARL </td>
   <td style="text-align:center;"> 0.17 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> DOROTHY </td>
   <td style="text-align:center;"> 0.13 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> OLIVIA </td>
   <td style="text-align:center;"> 0.06 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> FLORA </td>
   <td style="text-align:center;"> 0.06 </td>
  </tr>
</tbody>
</table>

`````
:::

::: {.cell-output-display}
`````{=html}
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E8 </td>
   <td style="text-align:center;"> 0.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E7 </td>
   <td style="text-align:center;"> 0.38 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E9 </td>
   <td style="text-align:center;"> 0.36 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E5 </td>
   <td style="text-align:center;"> 0.34 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E6 </td>
   <td style="text-align:center;"> 0.30 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E4 </td>
   <td style="text-align:center;"> 0.29 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E3 </td>
   <td style="text-align:center;"> 0.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E12 </td>
   <td style="text-align:center;"> 0.18 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E2 </td>
   <td style="text-align:center;"> 0.15 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E10 </td>
   <td style="text-align:center;"> 0.15 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E1 </td>
   <td style="text-align:center;"> 0.14 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E13 </td>
   <td style="text-align:center;"> 0.10 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E14 </td>
   <td style="text-align:center;"> 0.10 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E11 </td>
   <td style="text-align:center;"> 0.07 </td>
  </tr>
</tbody>
</table>

`````
:::
:::


The final rankings of both persons and groups should look familiar, for they are equivalent to the "dual" Bonacich centralities that can be calculated directly using methods from linear algebra as detailed in Bonacich (1991). That is, consider the standard one-mode person and group projections, which can be obtained from the original affiliation matrix as discussed in Breiger (1974). 

These are given by:

$$
B_p = AA^T
$$ {#eq-brei1}

$$
B_g = A^TA
$$ {#eq-brei1}

Where $B_p$ is the $|P| \times |P|$ person projection matrix (with off-diagonal cells indicating the number of groups two people have in common and diagonal cells indicting each person's number of memberships),  $B_g$ is the $|G| \times |G|$ group projection matrix (with off-diagonal cells indicating the number of people two groups have in common and diagonal cells indicting each group's number of members), and $A$ is the original affiliation matrix. For both persons and groups the projection matrices are shown in @tbl-proj-1 and @tbl-proj-2. 


::: {#tbl-proj .cell layout-ncol="1" tbl-cap='One mode projections for Southern Women Data.' tbl-subcap='["One mode projection of persons","One mode projection of groups"]'}
::: {.cell-output-display}
`````{=html}
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> EVELYN </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> LAURA </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> THERESA </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> BRENDA </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> CHARLOTTE </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> FRANCES </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> ELEANOR </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> RUTH </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> VERNE </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> MYRNA </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> KATHERINE </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> SYLVIA </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> NORA </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> HELEN </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> OLIVIA </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> FLORA </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> PEARL </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> DOROTHY </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
  </tr>
</tbody>
</table>

`````
:::

::: {.cell-output-display}
`````{=html}
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E1 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E4 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E5 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E6 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E7 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 10 </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E8 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 7 </td>
   <td style="text-align:center;"> 8 </td>
   <td style="text-align:center;"> 14 </td>
   <td style="text-align:center;"> 9 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E9 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 9 </td>
   <td style="text-align:center;"> 12 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E10 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E11 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E12 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 4 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 5 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 6 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E13 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E14 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 0 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 2 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 1 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
   <td style="text-align:center;"> 3 </td>
  </tr>
</tbody>
</table>

`````
:::
:::


Bonacich shows that vectors that will order people and groups in the same way as that shown in @tbl-final, can be obtained by solving the following system of linear equations:

$$
B_p c_p = \lambda c_p
$$ {#eq-bon1}

$$
B_g c_g = \lambda c_g
$$ {#eq-bon2}

Which means that $c_p$ is an eigenvector of the projection matrix $B_p$ and $c_g$ is an eigenvector of the projection matrix $B_g$. In fact, the person and group vectors of centrality scores that will order people and groups exactly as in @tbl-final, are the leading (first) eigenvectors of each respective projection matrix (Bonacich, 1991; Faust, 1997). These are shown in @tbl-eigen. As we can see, the (absolute) value for the eigenvectors of persons and groups in @tbl-eigen is identical to that shown in @tbl-final. The reason for this is that the reflective iterative method, is actually a way of computing the eigenvectors of a matrix! (It's called the "power" method and was first discovered by von Mises)



::: {#tbl-eigen .cell layout-ncol="2" tbl-cap='Leading Eigenvectors for projection matrices of Southern Women Data.' tbl-subcap='["Eigenvector scores of persons","Eigenvector scores of groups"]'}
::: {.cell-output-display}
`````{=html}
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> THERESA </td>
   <td style="text-align:center;"> -0.38 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> EVELYN </td>
   <td style="text-align:center;"> -0.34 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> BRENDA </td>
   <td style="text-align:center;"> -0.32 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> LAURA </td>
   <td style="text-align:center;"> -0.30 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> RUTH </td>
   <td style="text-align:center;"> -0.27 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> ELEANOR </td>
   <td style="text-align:center;"> -0.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> SYLVIA </td>
   <td style="text-align:center;"> -0.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> FRANCES </td>
   <td style="text-align:center;"> -0.25 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> VERNE </td>
   <td style="text-align:center;"> -0.21 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> KATHERINE </td>
   <td style="text-align:center;"> -0.20 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> CHARLOTTE </td>
   <td style="text-align:center;"> -0.19 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> NORA </td>
   <td style="text-align:center;"> -0.19 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> HELEN </td>
   <td style="text-align:center;"> -0.19 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> MYRNA </td>
   <td style="text-align:center;"> -0.17 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> PEARL </td>
   <td style="text-align:center;"> -0.17 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> DOROTHY </td>
   <td style="text-align:center;"> -0.13 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> OLIVIA </td>
   <td style="text-align:center;"> -0.06 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> FLORA </td>
   <td style="text-align:center;"> -0.06 </td>
  </tr>
</tbody>
</table>

`````
:::

::: {.cell-output-display}
`````{=html}
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E8 </td>
   <td style="text-align:center;"> -0.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E7 </td>
   <td style="text-align:center;"> -0.38 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E9 </td>
   <td style="text-align:center;"> -0.36 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E5 </td>
   <td style="text-align:center;"> -0.34 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E6 </td>
   <td style="text-align:center;"> -0.30 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E4 </td>
   <td style="text-align:center;"> -0.29 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E3 </td>
   <td style="text-align:center;"> -0.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E12 </td>
   <td style="text-align:center;"> -0.18 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E2 </td>
   <td style="text-align:center;"> -0.15 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E10 </td>
   <td style="text-align:center;"> -0.15 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E1 </td>
   <td style="text-align:center;"> -0.14 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E13 </td>
   <td style="text-align:center;"> -0.10 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E14 </td>
   <td style="text-align:center;"> -0.10 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> E11 </td>
   <td style="text-align:center;"> -0.07 </td>
  </tr>
</tbody>
</table>

`````
:::
:::



## References

Bonacich, P. (1991). Simultaneous group and individual centralities. *Social Networks*, 13(2), 155-168.

Breiger, R. L. (1974). The duality of persons and groups. *Social Forces*, 53(2), 181-190.

Davis, A., Gardner, B. B., & Gardner, M. R. (1941). *Deep South: A social anthropological study of caste and class*. University of Chicago Press

Faust, K. (1997). Centrality in affiliation networks. *Social Networks*, 19(2), 157-191.


