---
title: "SOCIOL 204 (Sociological Theorizing)"
subtitle: "Winter 2026 Reading Schedule"
format: 
  html:
    page-layout: full
---

## Theory and Theorizing
### Week 1 (January 7)
#### What is Theory?
- Abend, G. (2008). The meaning of 'Theory.' *Sociological Theory*, 26(2), 173-199. 
- Joas, H., & Knöbl, W. (2009). What is Theory? Pp. 1-19 in *Social Theory: Twenty Introductory Lectures*. Cambridge University Press 
- Davis, M. S. (1971). That's interesting! Towards a phenomenology of sociology and a sociology of phenomenology. *Philosophy of the Social Sciences*, 1(2), 309-344. 

#### Why is Theory?
- Besbris, M., & Khan, S. (2017). Less Theory. More Description. *Sociological Theory*, 35(2), 147-153.
- Healy, K. (2017). Fuck nuance. *Sociological Theory*, 35(2), 118-127. 
- Mears, A. (2017). Puzzling in sociology: On doing and undoing theoretical puzzles. *Sociological Theory*, 35(2), 138-146.

## Habits, Bodies, and Practices
### Week 2 (January 14)
- Dubrule, A. (2022). Gender and Habit: John Dewey and Iris Marion Young on Embodiment and Transformation. *The Pluralist*, 17(1), 45-51. 
- Liao, S. Y., & Huebner, B. (2021). Oppressive things. *Philosophy and Phenomenological Research*, 103(1), 92-113. 
- Luft, A. (2023). The moral career of the genocide perpetrator: Cognition, emotions, and dehumanization as a consequence, not a cause, of violence. *Sociological Theory*, 41(4), 324-351.
- Sullivan, S. (2000). Reconfiguring gender with John Dewey: Habit, bodies, and cultural change. *Hypatia*, 15(1), 23-42. 
- Young, I. M. (1980). Throwing like a girl: A phenomenology of feminine body comportment motility and spatiality. *Human Studies*, 3(1), 137-156.

### Week 3 (January 21)
- Engman, A., & Cranford, C. (2016). Habit and the Body: Lessons for Social Theories of Habit from the Experiences of People with Physical Disabilities. *Sociological Theory*, 34(1), 27-44.
- Haslanger, S. (2018). What is a social practice? *Royal Institute of Philosophy Supplements*, 82, 231-247. 
- Ngo, H. (2016). Racist habits: A phenomenological analysis of racism and the habitual body. *Philosophy & Social Criticism*, 42(9), 847-872. 
- Pagis, M. (2010). From abstract concepts to experiential knowledge: Embodying enlightenment in a meditation center. *Qualitative Sociology*, 33(4), 469-489. 
- Winchester, D. (2008). Embodying the faith: Religious practice and the making of a Muslim moral habitus. *Social Forces*, 86(4), 1753-1780. 

## Fields, Ecologies, Institutions, and Organization

### Week 4 (January 28)
- Abbott, A. (2005). Linked ecologies: States and universities as environments for professions. *Sociological Theory*, 23(3), 245-274. 
- Beckert, J. (2010). Institutional isomorphism revisited: Convergence and divergence in institutional change. *Sociological Theory*, 28(2), 150-166.
- Dimaggio, P. J., & Powell, W. W. (1983). The iron cage revisited: Institutional isomorphism and collective rationality in organizational fields. *American Sociological Review*, 48(2), 147-160. 
- Garcelon, M. (2010). The missing key: Institutions, networks, and the project of neoclassical sociology. *Sociological Theory*, 28(3), 326-353.
- Wang, Y. (2016). Homology and isomorphism: Bourdieu in conversation with New Institutionalism. *The British Journal of Sociology*, 67(2), 348-370. 

### Week 5 (February 11)
- Armstrong, E. A., & Bernstein, M. (2008). Culture, power, and institutions: A multi‐institutional politics approach to social movements. *Sociological Theory*, 26(1), 74-99.
- Fligstein, N., & McAdam, D. (2011). Toward a general theory of strategic action fields. *Sociological Theory*, 29(1), 1-26.
- Krause, M. (2018). How fields vary. *The British Journal of Sociology*, 69(1), 3-22. 
- Ray, V. (2019). A theory of racialized organizations. *American Sociological Review*, 84_(1), 26-53. 
- Meyer, J. W., & Bromley, P. (2013). The worldwide expansion of 'organization'. *Sociological Theory*, 31(4), 366-389.

## Interaction, Situations, and Phenomenology
### Week 6 (February 18)
- Atkinson, W. (2010). Phenomenological additions to the Bourdieusian toolbox: Two problems for Bourdieu, two solutions from Schutz. *Sociological Theory*, 28(1), 1-19.
- Cetina, K. K. (2009). The synthetic situation: Interactionism for a global world. *Symbolic Interaction*, 32(1), 61-87. 
- Fligstein, N. (2001). Social skill and the theory of fields. *Sociological Theory*, 19(2):105-125. 
- Hallett, T., & Hawbaker, A. (2021). The case for an inhabited institutionalism in organizational research: interaction, coupling, and change reconsidered. *Theory and Society*, 50(1), 1-32. 
- Itzigsohn, J., & Brown, K. (2015). Sociology and the theory of double consciousness: WEB Du Bois’s phenomenology of racialized subjectivity. *Du Bois Review*, 12(2), 231-248.

### Week 7 (February 25)
- Voronov, M., & Weber, K. (2020). People, actors, and the humanizing of institutional theory. *Journal of Management Studies*, 57(4), 873-884.
- Timmermans, S., & Tavory, I. (2020). Racist Encounters: A Pragmatist Semiotic Analysis of Interaction. *Sociological Theory*, 38(4), 295-317. 
- Surak, K. (2017). Rupture and rhythm: A phenomenology of national experiences. *Sociological Theory*, 35(4), 312-333.
- Voronov, M., Glynn, M. A., & Weber, K. (2022). Under the radar: institutional drift and non‐strategic institutional change. *Journal of management Studies*, 59(3), 819-842. 
- Tavory, I., & Eliasoph, N. (2013). Coordinating futures: Toward a theory of anticipation. *American Journal of Sociology*, 118(4), 908-942.

## Networks, Relations, and Structures

### Week 8 (March 4)
- Crossley, N. (2022). A Dependent Structure of Interdependence: Structure and Agency in Relational Perspective. *Sociology*, 56(1), 166-182. 
- Erikson, E. (2013). Formalist and relationalist theory in social network analysis. *Sociological Theory*, 31_(3), 219-242.
- Fuhse, J. A. (2009). The meaning structure of social networks. *Sociological theory*, 27(1), 51-73.
- Sewell Jr, W. H. (1992). A theory of structure: Duality, agency, and transformation. *American Journal of Sociology*, 98(1), 1-29.
- Reed, I. A. (2017). Chains of power and their representation. *Sociological Theory*, 35(2), 87-117.

### Week 9 (May 23)
- Dépelteau, F. (2008). Relational Thinking: A Critique of Co‐Deterministic Theories of sructure and Agency.*Sociological Theory*,26(1), 51-73 
- Elder Vass, D. (2008). Integrating institutional, relational and embodied structure: an emergentist perspective. *The British Journal of Sociology*, 59(2), 281-299.
- Emirbayer, M. (1997). Manifesto for a relational sociology. *American Journal of Sociology*, 103_(2), 281-317. 
- Haslanger, S. (2016). What is a (social) structural explanation? *Philosophical Studies*, 173, 113–130.
- Saito, H. (2011). An actor-network theory of cosmopolitanism. *Sociological Theory*, 29(2), 124-149.

## Culture, Cognition, and Action

### Week 10 (March 11)
- Brett, G. (2022). Dueling with Dual-Process Models: Cognition, Creativity, and Context. *Sociological Theory*, 40(2), 179-201.
- Freeman, K. J., Condron, D. J., & Steidl, C. R. (2020). Structures of stratification: Advancing a sociological debate over culture and resources. *Critical Sociology*, 46_(2), 191-206. 
- Swidler, A. (1986). Culture in action: Symbols and strategies. *American Sociological Review*, 51,:273–286. 
- Leschziner, V., & Green, A. I. (2013). Thinking about food and sex: Deliberate cognition in the routine practices of a field. *Sociological Theory*, 31(2), 116-144.
- Vaisey, S. (2009). Motivation and justification: Toward a dual-process theory of culture in action. *American Journal of Sociology*, 114(6):1675–1715. 

