---
title: "SOCIOL 208B Reading Schedule (Spring 2024)"
format: 
  html:
    page-layout: full
---

## Week 1: Networks As Theory and Perspective
### Tuesday, April 2
- Wellman, B. (1988). Structural Analysis: From Method and Metaphor To Theory and Substance. In B. Wellman & S. D. Berkowitz (Eds.), *Social Structures: A Network Approach*. (Pp. 19–61). Cambridge University Press. 
- Freeman, L. (2004). *The Development of Social Network Analysis*. Vancouver, BC: Empirical Press (Introduction, and Chap. 9)

### Thursday, April 4
- Emirbayer, M. (1997). Manifesto For A Relational Sociology. *American Journal of Sociology*, 103(2), 281–317. 
- Erikson, E. (2013). Formalist and Relationalist Theory In Social Network Analysis. *Sociological Theory*, 31(3), 219–242.
- Mische, A. (2011). Relational Sociology, Culture, and Agency. In J. Scott & P. J. Carrington (Eds.), *The Sage Handbook of Social Network Analysis* (Pp. 80–97). Sage. 

## Week 2: The Greatest Hits    
### Tuesday, April 9
- White, H. C., Boorman, S. A., & Breiger, R. L. (1976). Social Structure From Multiple Networks. I. Blockmodels of Roles and Positions. *American Journal of Sociology*, 81(4), 730–780. 
- Breiger, R. L. (1974). The Duality of Persons and Groups. *Social Forces*, 53(2), 181–190. 
- Freeman, L. C. (1978). Centrality in social networks conceptual clarification. *Social networks*, 1(3), 215-239. 

### Thursday, April 11
- Granovetter, M. S. (1973). The Strength of Weak Ties. *American Journal of Sociology*, 78(3), 1360–1380.
     - Rejection letter from *American Sociological Review* of the first (1969) version of the paper 
     - Granovetter, M. S. (1969) ``Alienation Reconsidered: The Strength of Weak Ties.'' Reprinted in *Connections* 5(2): 4-16. 
- Centola, D., & Macy, M. (2007). Complex Contagions and the Weakness of Long Ties. *American Journal of Sociology*, 113(3), 702-734. 
- McPherson, M., Smith-Lovin, L., & Cook, J. M. (2001). Birds of a feather: Homophily in social networks. *Annual Review of Sociology*, 27(1), 415-444. 


## Week 3: Brokerage and Intermediation
### Tuesday, April 16
- Gould, R. V., & Fernandez, R. M. (1989). Structures of Mediation: A Formal Approach To Brokerage In Transaction Networks. *Sociological Methodology*, 89-126. 
- Obstfeld, D., Borgatti, S.P. and Davis, J. (2014). Brokerage As a Process: Decoupling Third Party Action From Social Network Structure. *Research In The Sociology of Organizations*, 40), 135-159. 
- Stovel, K., & Shaw, L. (2012). Brokerage. *Annual Review of Sociology*, 38, 139-158. 

### Thursday, April 18
- Burt, R. S. (2004). Structural Holes and Good Ideas. *American Journal of Sociology*, 110(2), 349-399.[pdf]
- Goldberg, A., Srivastava, S. B., Manian, V. G., Monroe, W., & Potts, C. (2016). Fitting In Or Standing Out? The Tradeoffs of Structural and Cultural Embeddedness. *American Sociological Review*, 81(6), 1190-1222. 
- Aral, S., & Van Alstyne, M. (2011). The diversity-bandwidth trade-off. *American Journal of Sociology*, 117(1), 90-171. 

## Week 4: Networks In Science
### Tuesday, April 23
- Moody, J. (2004). The Structure of A Social Scientific Collaboration Network. *American Sociological Review*, 69, 213-238. 
- Shwed, U., & Bearman, P. S. (2010). The Temporal Structure of Scientific Consensus Formation. *American Sociological Review*, 75(6), 817-840. 
- Moody, J., & Light, R. (2006). A view from above: The evolving sociological landscape. *The American Sociologist*, 37(2), 67-86. 

### Thursday, April 25
- Foster, J. G., Rzhetsky, A., & Evans, J. A. (2015). Tradition and Innovation In Scientists’ Research Strategies. *American Sociological Review*, 80(5), 875-908. 
- Mcmahan, P., & Mcfarland, D. A. (2021). Creative Destruction: The Structural Consequences of Scientific Curation. *American Sociological Review*, 86(2), 341-376. 

## Week 5: Collaboration, Creativity, and Field Dynamics
### Tuesday, April 30
- Vedres, B., & Stark, D. (2010). Structural Folds: Generative Disruption In Overlapping Groups. *American Journal of Sociology*, 115(4), 1150-1190. 
- Uzzi, B, & Spiro, J. (2005). Collaboration and Creativity: The Small World Problem. *American Journal of Sociology*, 111, 447-504. 

### Thursday, May 2
- Powell, W. W., White, D. R., Koput, K. W., & Owen-Smith, J. (2005). Network Dynamics and Field Evolution: The Growth of Interorganizational Collaboration In The Life Sciences. *American Journal of Sociology*, 110(4), 1132-1205. 
- Rossman, G., Esparza, N., & Bonacich, P. (2010). I’d Like To Thank The Academy, Team Spillovers, and Network Centrality. *American Sociological Review*, 75(1), 31-51. 

## Week 6: Networks and Culture and Culture in Networks
### Tuesday, May 7
- Breiger, R. L. (2010). Dualities of culture and structure: Seeing through cultural holes. Pp. 37-47 in *Relationale soziologie*. VS Verlag für Sozialwissenschaften. 
- Lizardo, 0. (2023). Culture and Networks. Pp. 188-201 in *The SAGE Handbook of Social Network Analysis*. SAGE Publications Ltd. 
- Lewis, K., & Kaufman, J. (2018). The Conversion of Cultural Tastes Into Social Network Ties. *American Journal of Sociology*, 123(6), 1684-1742. 

### Thursday, May 9
- Fuhse, J. A. (2009). The Meaning Structure of Social Networks. *Sociological Theory*, 27(1), 51-73. 
- Ikegami, E. (2000). A Sociological Theory of Publics: Identity and Culture As Emergent Properties In Networks. *Social Research*, 989-1029. 
- Mützel, S., & Breiger, R. (2021). Duality Beyond Persons and Groups. In  *The Oxford Handbook of Social Networks*. Oxford University Press. 

## Week 7: Difussion In Networks
### Tuesday, May 14
- Dellaposta, D., Shi, Y., & Macy, M. (2015) Why Do Liberals Drink Lattes?. *American Journal of Sociology*, 120(5), 1473-1511. 
- Centola, D. (2015). The social origins of networks and diffusion. *American Journal of Sociology*, 120(5), 1295-1338. 
- Becker, S. O., Hsiao, Y., Pfaff, S., & Rubin, J. (2020). Multiplex Network Ties and the Spatial Diffusion of Radical Innovations: Martin Luther's Leadership In The Early Reformation. *American Sociological Review*, 85(5), 857-894. 

### Thursday, May 16
- Goldberg, A., & Stein, S. K. (2018). Beyond Social Contagion: Associative Diffusion and The Emergence of Cultural Variation. *American Sociological Review*, 83(5), 897-932. 
- Bail, C. A., Brown, T. W., & Mann, M. (2017). Channeling hearts and minds: Advocacy organizations, cognitive-emotional currents, and public conversation. *American Sociological Review*, 82(6), 1188-1213. 

## Week 8: Networks In History  
### Tuesday, May 21
- Padgett, J. F., & Ansell, C. K. (1993). Robust Action and the Rise of the Medici, 1400-1434. *American Journal of Sociology*, 98(6), 1259–1319. 
- Gould, R. V. (1991). Multiple Networks and Mobilization In The Paris Commune, 1871. *American Sociological Review*, 56(6), 716-729. 
- Erikson, E., & Feltham, E. (2021). Historical Network Research. In *The Oxford Handbook of Social Networks*. Oxford University Press. 

### Thursday, May 23
- Erikson, E., & Bearman, P. (2006). Malfeasance and the Foundations For Global Trade: The Structure of English Trade In The East Indies, 1601–1833. *American Journal of Sociology*, 112(1), 195-230. 
- Bearman, P., Faris, R., & Moody, J. (1999). Blocking The Future: New Solutions For Old Problems In Historical Social Science. *Social Science History*, 23(4), 501-533. 

## Week 9: Networks and Inequality
### Tuesday, May 28
- Gould, R. V. (2002). The Origins of Status Hierarchies: A Formal Theory and Empirical Test. *American Journal of Sociology*, 107(5), 1143-1178. 
- Gondal, N. (2015). Inequality preservation through uneven diffusion of Cultural materials across stratified groups. *Social Forces*, 93(3), 1109-1137. 
- Thomas, R. J., & Mark, N. P. (2013). Population size, network density, and the emergence of inherited inequality. *Social Forces*, 92(2), 521-544. 

### Thursday, May 30
- Burris, V. (2004). The Academic Caste System: Prestige Hierarchies In PhD Exchange Networks. *American Sociological Review*, 69, 239-264. 
- Fowler, J. H., Grofman, B., & Masuoka, N. (2007). Social networks in political science: Hiring and placement of Ph.Ds, 1960–2002. *PS: Political Science & Politics*, 40(4), 729-739. 
- Clauset, A., Arbesman, S., & Larremore, D. B. (2015). Systematic inequality and hierarchy in faculty hiring networks. *Science Advances*, 1(1), e1400005. 
- Gondal, N. (2018). Duality of departmental specializations and PhD exchange: A Weberian analysis of status in interaction using multilevel exponential random graph models (mERGM). *Social Networks*, 55, 202-212. 


## Week 10: Networks and The Micro/Macro Link
### Tuesday, June 4
- Mcfarland, D. A., Moody, J., Diehl, D., Smith, J. A., & Thomas, R. J. (2014). Network Ecology and Adolescent Social Structure. *American Sociological Review*, 79(6), 1088-1121. 
- Bearman, P. S., Moody, J., & Stovel, K. (2004). Chains of Affection: The Structure of Adolescent Romantic and Sexual Networks. *American Journal of Sociology*, 110(1), 44-91. 

### Thursday, June 6 
- Levy, B. L., Phillips, N. E., & Sampson, R. J. (2020). Triple Disadvantage: Neighborhood Networks of Everyday Urban Mobility and Violence In US Cities. *American Sociological Review*, 85(6), 925-956. 
- Papachristos, A. V. (2009). Murder By Structure: Dominance Relations and the Social Structure of Gang Homicide. *American Journal of Sociology*, 115(1), 74-128. 