---
title: "SOCIOL 204 (Sociological Theorizing)"
subtitle: "Expanded Reading List"
format: 
  html:
    page-layout: full
---

# Readings

## Theory and Theorizing
- Abend, G. (2008). The meaning of 'Theory.' *Sociological Theory*, 26(2), 173-199. 
- Alexander, J. C. (1987). What is Theory? Twenty Lectures: Sociological Theory Since World War II. Columbia University Press. (Pp. 1-21).
- Craib, I. (1992) What's Wrong with Theory and Why We Still Need it. Modern Social Theory. St Martin's Press. (Pp. 1-13).
- Craib, I. (1992) Cutting a Path Through the Jungle. Modern Social Theory. St Martin's Press. (Pp. 15-31).
- Davis, M. S. (1971). That's interesting! Towards a phenomenology of sociology and a sociology of phenomenology. *Philosophy of the Social Sciences*, 1(2), 309-344. 
- Healy, K. (2017). Fuck nuance. *Sociological Theory*, 35(2), 118-127. 
- Heiskala, R. (2014). Evidence and interest in social theory An ontological-practical approach. *Acta Sociologica*, 57(4), 279-292.
- Joas, H., & Knöbl, W. (2009). What is Theory? Pp. 1-19 in *Social Theory: Twenty Introductory Lectures*. Cambridge University Press 
- Martin, J. L. (2015) On Theory in Sociology. Pp. 1-44 in *Thinking Through Theory*. W. W. Norton

## Habit and Practice 
- Archer, M. S. (2010). Routine, reflexivity, and realism. *Sociological Theory*, 28(3), 272-303. 
-  Camic, C.  (1986). The Matter of Habit. *American Journal of Sociology* 91,(5), 1039-1087.
- Casey, E. S. (1984). Habitual body and memory in Merleau-Ponty. In *Phenomenology and the Human Sciences* (pp. 39-57). Dordrecht: Springer Netherlands.
- Crossley, N. (2013). Habit and habitus. *Body & Society*, 19(2-3), 136-161. 
- Dalton, B. (2004). Creativity, Habit, and the Social Products of Creative Action: Revising Joas, Incorporating Bourdieu. *Sociological Theory*, 22(4):603-622 
- Dubrule, A. (2022). Gender and Habit: John Dewey and Iris Marion Young on Embodiment and Transformation. *The Pluralist*, 17(1), 45-51. 
- Elder‐Vass, D. (2007). Reconciling Archer and Bourdieu in an emergentist theory of action. *Sociological Theory*, 25(4), 325-346.
- Engman, A., & Cranford, C. (2016). Habit and the Body: Lessons for Social Theories of Habit from the Experiences of People with Physical Disabilities. *Sociological Theory*, 34(1), 27-44.
- Gold, T. (2022). Contentious Tactics as Jazz Performances: A Pragmatist Approach to the Study of Repertoire Change. *Sociological Theory*, 40(3), 249-271. 
- Gross, N. (2009). A pragmatist theory of social mechanisms. *American Sociological Review*, 74(3), 358-379. 
- Haslanger, S. (2018). What is a social practice? *Royal Institute of Philosophy Supplements*, 82, 231-247. 
- King, A. (2000). Thinking with Bourdieu against Bourdieu: A'practical'critique of the habitus. *Sociological Theory*, 18(3), 417-433.
- Lau, R. W. (2004). Habitus and the Practical Logic of Practice: An Interpretation. *Sociology*, 38(2), 369-387
- Liao, S. Y., & Huebner, B. (2021). Oppressive things. *Philosophy and Phenomenological Research*, 103(1), 92-113. 
- Ngo, H. (2016). Racist habits: A phenomenological analysis of racism and the habitual body. *Philosophy & Social Criticism*, 42(9), 847-872. 
- Ostrow, J. (1987). Habit and inhabitance: an analysis of experience in the classroom. *Human Studies*, 213-224.
- Pagis, M. (2010). From abstract concepts to experiential knowledge: Embodying enlightenment in a meditation center. *Qualitative Sociology*, 33(4), 469-489. 
- Reckwitz, A. (2002). Toward a theory of social practices: A development in culturalist theorizing. *European Journal of Social Theory*, (2), 243-263. 
- Sullivan, S. (2000). Reconfiguring gender with John Dewey: Habit, bodies, and cultural change. *Hypatia*, 15(1), 23-42. 
- Swidler, A. (2001). What anchors cultural practices. Pp. 74-92 in Schatzki, T. R., Knorr-Cetina, K., and Savigny, E. V., editors, *The Practice Turn in Contemporary Theory*. Routledge.
- Whitford, J. (2002). Pragmatism and the untenable dualism of means and ends: Why rational choice theory does not deserve paradigmatic privilege. *Theory and Society*, 31(3), 325-363.
- Winchester, D. (2008). Embodying the faith: Religious practice and the making of a Muslim moral habitus. *Social Forces*, 86(4), 1753-1780. 

## Fields, Ecologies, and Institutions
- Abbott, A. (2005). Linked ecologies: States and universities as environments for professions. *Sociological Theory*, *23_(3), 245-274. 
- Armstrong, E. A., & Bernstein, M. (2008). Culture, power, and institutions: A multi‐institutional politics approach to social movements. *Sociological Theory*, 26(1), 74-99.
- Barley, S. R., & Tolbert, P. S. (1997). Institutionalization and structuration: Studying the links between action and institution. *Organization Studies*, 18(1), 93-117. 
- Beckert, J. (2010). Institutional isomorphism revisited: Convergence and divergence in institutional change. *Sociological Theory*, 28(2), 150-166.
- Buchholz, L. (2016). What is a global field? Theorizing fields beyond the nation-state. *The Sociological Review*, 64(2\_suppl), 31-60. 
- Dimaggio, P. J., & Powell, W. W. (1983). The iron cage revisited: Institutional isomorphism and collective rationality in organizational fields. *American Sociological Review*, 48(2), 147-160. 
- Friedland, R. and Alford, R. (1991). Bringing society back in: Symbols, practices, and institutional contradictions. Pp. 232-263 in DiMaggio, P. and Powell, W., editors, *The New Institutionalism in Organizational Analysis*. University of Chicago Press. 
- Fligstein, N., & McAdam, D. (2011). Toward a general theory of strategic action fields. *Sociological Theory*, 29(1), 1-26.
- Frank, D. J., & Meyer, J. W. (2002). The profusion of individual roles and identities in the postwar period. *Sociological Theory*, *20_(1), 86-105. 
- Go, J. (2008). Global fields and imperial forms: Field theory and the British and American empires. *Sociological Theory*, 26(3), 201-229.
- Green, A. I. (2008). The Social organization of desire: The sexual fields approach. *Sociological Theory*, 26(1), 25-50
- Jepperson, R. L. (1991). Institutions, institutional effects, and institutionalism. Pp. 143-163 in DiMaggio, P. and Powell, W., editors, *The New Institutionalism in Organizational Analysis*. The University of Chicago Press. 
- Kluttz, D. N., & Fligstein, N. (2016). Varieties of sociological field theory. In *Handbook of Contemporary Sociological Theory* (pp. 185-204). Springer. 
- Krause, M. (2018). How fields vary. *The British Journal of Sociology*, *69_(1), 3-22. 
- Liu, S., & Emirbayer, M. (2016). Field and Ecology. *Sociological Theory*, 34(1), 62-79. 
- Martin, J. L. (2003). What is field theory? *American Journal of Sociology*, 109_(1), 1-49. 
- Martin, P. Y. (2004). Gender as social institution. *Social Forces*, 82(4), 1249-1273.
- Meyer, J. W., & Rowan, B. (1977). Institutionalized organizations: Formal structure as myth and ceremony. *American Journal of Sociology*, *83_(2), 340-363. 
- Meyer, J. W., & Jepperson, R. L. (2000). The 'actors' of modern society: The cultural construction of social agency. *Sociological Theory*, *18_(1), 100-120. 
- Meyer, J. W., Boli, J., Thomas, G. M., & Ramirez, F. O. (1997). World society and the nation-state. *American Journal of Sociology*, *103_(1), 144-181. 
- Schneiberg, M., & Clemens, E. S. (2006). The typical tools for the job: Research strategies in institutional analysis. *Sociological Theory*, 24(3), 195-227.
- Silber, I. F. (1995). Space, fields, boundaries: The rise of spatial metaphors in contemporary sociological theory. *Social Research*, 323-355.
- Steinmetz, G. (2016). Social fields, subfields and social spaces at the scale of empires: Explaining the colonial state and colonial sociology. *The Sociological Review*, 64(2), 98-123.
- Strang, D., & Meyer, J. W. (1993). Institutional conditions for diffusion. *Theory and Society*, 487-511.
- Wang, Y. (2016). Homology and isomorphism: Bourdieu in conversation with New Institutionalism. *The British Journal of Sociology*, 67(2), 348-370. 
- Wimmer, A. (2021). Domains of diffusion: How culture and institutions travel around the world and with what consequences. *American Journal of Sociology*, *126_(6), 1389-1438. 

## Interactionism and Phenomenology
- Atkinson, W. (2010). Phenomenological additions to the Bourdieusian toolbox: Two problems for Bourdieu, two solutions from Schutz. *Sociological Theory*, 28(1), 1-19.
- Cetina, K. K. (2009). The synthetic situation: Interactionism for a global world. *Symbolic Interaction*, 32(1), 61-87. 
- Crawley, S. L. (2022). Queering doing gender: The curious absence of ethnomethodology in gender studies and in sociology. *Sociological Theory*, 40(4), 366-392.
- Crossley, N. (2001). The phenomenological habitus and its construction. *Theory and society*, *30_(1), 81-120.
- Fligstein, N. (2001). Social skill and the theory of fields. *Sociological Theory*, 19(2):105-125. 
- Hallett, T., & Hawbaker, A. (2021). The case for an inhabited institutionalism in organizational research: interaction, coupling, and change reconsidered. *Theory and Society*, *50_(1), 1-32. 
- Heiskala, R. (2011). The meaning of meaning in sociology. The achievements and shortcomings of Alfred Schutz's phenomenological sociology. *Journal for the Theory of Social Behaviour*, 41(3), 231-246.
- Hitlin, S., & Elder, G. H. (2007). Time, self, and the curiously abstract concept of agency. *Sociological Theory*, 25(2), 170-191
- Itzigsohn, J., & Brown, K. (2015). Sociology and the theory of double consciousness: WEB Du Bois’s phenomenology of racialized subjectivity. *Du Bois Review*, 12(2), 231-248.
- Reay, M. (2010). Knowledge distribution, embodiment, and insulation. *Sociological Theory*, *28_(1), 91-107.
- Surak, K. (2017). Rupture and Rhythm: A Phenomenology of National Experiences. *Sociological Theory*, 35(4), 312-333.
- Tavory, I., & Fine, G. A. (2020). Disruption and the Theory of the Interaction Order. *Theory and Society*, *49_(3), 365-385. 
- Tavory, I. (2018). Between situations: Anticipation, rhythms, and the theory of interaction. *Sociological Theory*, *36_(2), 117-133.
- Tavory, I., & Winchester, D. (2012). Experiential careers: the routinization and de-routinization of religious life. *Theory and Society*, 41, 351-373.
- Tavory, I., & Eliasoph, N. (2013). Coordinating Futures: Toward a Theory of Anticipation. *American Journal of Sociology*, 118(4), 908-942.
- Timmermans, S., & Tavory, I. (2020). Racist Encounters: A Pragmatist Semiotic Analysis of Interaction. *Sociological Theory*, 38(4), 295-317. 
- Young, I. M. (1980). Throwing like a girl: A phenomenology of feminine body comportment motility and spatiality. *Human Studies*, 3(1), 137-156.
- Yancy, G. (2008). Elevators, social spaces and racism: A philosophical analysis. *Philosophy & Social Criticism*, 34(8), 843-876.

## Networks, Relations, and Structures
- Bourdieu, P. (1985). The social space and the genesis of groups. *Social science information*, 24(2), 195-220.
- Crossley, N. (2022). A Dependent Structure of Interdependence: Structure and Agency in Relational Perspective. *Sociology*, 56(1), 166-182. 
- Dépelteau, F. (2008). Relational Thinking: A Critique of Co‐Deterministic Theories of sructure and Agency.*Sociological Theory*,26(1), 51-73 
- Elder Vass, D. (2008). Integrating institutional, relational and embodied structure: an emergentist perspective. *The British Journal of Sociology*, 59(2), 281-299 
- Haslanger, S. (2016). What is a (social) structural explanation? *Philosophical Studies*, 173, 113–130.
- Haslanger, S. (2015). Social structure, narrative and explanation. *Canadian Journal of Philosophy*, 45(1), 1-15.
- Joas, H., & Knöbl, W. (2009). Structuralism and Poststructuralism. Pp. 339-370 in *Social Theory: Twenty Introductory Lectures*. Cambridge University Press. 
- Erikson, E. (2013). Formalist and relationalist theory in social network analysis. *Sociological Theory*, 31_(3), 219-242.
- Fuhse, J. A. (2009). The meaning structure of social networks. *Sociological theory*, 27(1), 51-73. 
- Emirbayer, M. (1997). Manifesto for a relational sociology. *American Journal of Sociology*, 103_(2), 281-317. 
- Heiskala, R. (2001). Theorizing power: Weber, Parsons, Foucault and neostructuralism. *Social Science Information*, 40(2), 241-264
- Leschziner, V., & Brett, G. (2021). Symbol Systems and Social Structures. Pp. pp. 559-582 in *Handbook of Classical Sociological Theory*. Springer. 
- Maryanski, A. and Turner, J. (1991). The off
spring of functionalism: French and British structuralism. *Sociological Theory*, 9(1):106-111.
- Mische, A. (2011) Relational sociology, culture, and agency. Pp. 80-97 in *The Sage handbook of Social Network Analysis*. Sage Publications. 
- Porpora, D. V. (1989). Four concepts of social structure. *Journal for the Theory of Social Behaviour*, 19(2), 195–211
- Ray, V. (2019). A theory of racialized organizations. *American Sociological Review*, 84_(1), 26-53. 
- Ritchie, K. (2020). Social structures and the ontology of social groups. *Philosophy and Phenomenological Research*, 100(2), 402-424.
- Reed, I. A. (2013). Power: Relational, discursive, and performative dimensions. *Sociological Theory*, 31_(3), 193-218.
- Reed, I. A. (2017). Chains of power and their representation. Sociological Theory, 35(2), 87-117.
- Risman, B. J. (2004). Gender As a Social Structure: Theory Wrestling with Activism. *Gender & Society*, 18(4), 429-450. 
- Saito, H. (2011). An actor-network theory of cosmopolitanism. *Sociological Theory*, 29(2), 124-149.
- Sewell Jr, W. H. (1992). A theory of structure: Duality, agency, and transformation. *American Journal of Sociology*, 98(1), 1-29.
- Singh, S. (2016). What Is Relational Structure? Introducing History to the Debates on the Relation between Fields and Social Networks. *Sociological Theory*, 34(2), 128-150.

## Culture, Cognition, and Action
- Abramson, C. M. (2012). From 'either‐or' to 'when and how': A context‐dependent model of culture in action. *Journal for the Theory of Social Behaviour*, 42(2), 155-180. 
- Alexander, J. C. (1988).  Action and its Environments  Pp. 301-333 in *Action and its Environments: Toward a New Synthesis*. Columbia University Press, New York. 
- Ayala Hurtado, E. (2022). Narrative continuity/rupture: Projected professional futures amid pervasive employment precarity. *Work and Occupations*, 49(1), 45-78.
- Brett, G. (2022). Dueling with Dual-Process Models: Cognition, Creativity, and Context. *Sociological Theory*, 40(2), 179-201. 
- Eckstein, H. (1996). Culture as a foundation concept for the social sciences. *Journal of Theoretical Politics*, (4), 471-497.
- Eliasoph, N., & Lichterman, P. (2003). Culture in interaction. *American Journal of Sociology*, 108(4), 735-794. 
- Emirbayer, M., & Mische, A. (1998). What is agency? *American Journal of Sociology*, 103(4), 962-1023. 
- Emirbayer, M., & Goodwin, J. (1994). Network analysis, culture, and the problem of agency. *American Journal of Sociology*, 99(6), 1411-1454.
- Freeman, K. J., Condron, D. J., & Steidl, C. R. (2020). Structures of stratification: Advancing a sociological debate over culture and resources. *Critical Sociology*, 46_(2), 191-206. 
- Haslanger, S. (2019). Cognition as a social skill. *Australasian Philosophical Review*, (1), 5-25. 
- Hays, S. (1994). Structure and agency and the sticky problem of culture. *Sociological theory*, 57-72. 
- Joas, H., & Knöbl, W. (2009). The Classical Attempt at Synthesis. Pp. 20-42 in *Social Theory: Twenty Introductory Lectures*. Cambridge University Press. 
- Leschziner, V., & Green, A. I. (2013). Thinking about Food and Sex Deliberate Cognition in the Routine Practices of a Field. *Sociological Theory*, 31(2), 116-144
- Lizardo, O., & Strand, M. (2010). Skills, toolkits, contexts and institutions: Clarifying the relationship between different approaches to cognition in cultural sociology. *Poetics*, 38(2), 205-228. 
- Luft, A. (2020). Theorizing moral cognition: Culture in action, situations, and relationships. *Socius*, , 2378023120916125. 
- Luft, A. (2023). The moral career of the genocide perpetrator: Cognition, emotions, and dehumanization as a consequence, not a cause, of violence. *Sociological Theory*, 41(4), 324-351.
- Miles, A. (2014). Addressing the problem of cultural anchoring an identity-based model of culture in action. *Social Psychology Quarterly*, 77(2), 210-227
- Patterson, O. (2015). The nature and dynamics of cultural processes. In *The cultural Matrix: Understanding Black Youth* (pp. 25-44). Harvard University Press.
- Reed, I. A., & Weinman, M. (2019). Agency, power, modernity: A manifesto for social theory. *European Journal of Cultural and Political Sociology*, (1), 6-50. 
- Sendroiu, I. (2022). 'All the old illusions': on guessing at being in crisis. *Sociological Theory*, 40(4), 297-321.
- Strand, M., & Lizardo, O. (2017). The hysteresis effect: Theorizing mismatch in action. *Journal for the Theory of Social Behaviour*, 47(2), 164-194.
- Sewell, W. H. (2005). The concept(s) of culture. Pp. 152-174 in *Logics of History*. University of Chicago Press. 
- Spillman, L. (1995). Culture, social structures, and discursive fields. *Current Perspectives in Social Theory*, 15:129-154.
- Silver, D. (2011). The moodiness of action. *Sociological Theory*, *29_(3), 199-222. 
- Swidler, A. (1986). Culture in action: Symbols and Strategies. *American Sociological Review*, 51,:273–286. 
- Vaisey, S. (2009). Motivation and justification: Toward a dual-process theory of culture in action. *American Journal of Sociology*, 114(6):1675–1715. 
- Winchester, D. (2016). A hunger for God: embodied metaphor as cultural cognition in action. *Social Forces*, 95(2), 585-606. 
- Winchester, D., & Green, K. D. (2019). Talking your self into it: How and when accounts shape motivation for action. *Sociological Theory*, 37(3), 257-281. 
- Zilberstein, S., Lamont, M., & Sanchez, M. (2023). Recreating a Plausible Future: Combining Cultural Repertoires in Unsettled Times. *Sociological Science*, 10, 348-373. 
