---
title: "SOCIOL 208B Syllabus"
bibliography: networks.bib
date: "`r Sys.Date()`"
format: 
  html:
    page-layout: full
---

**THIS IS A LIVE DOCUMENT CHECK REGULARLY FOR CHANGES**

### Course Information
- Department: Sociology (SOCIOL)  
- Name: SOCIOL 208B - Social Networks ~~Methods~~  
- Lecture Days: Tuesdays and Thursdays
- Lecture Time: 12:30p-1:45p
- Lecture Location: **Bunche 2150**

### Instructor Information
- Name: Omar Lizardo  
- Position: Professor, UCLA Sociology  
- Email: [olizardo@g.ucla.edu](mailto:olizardo@g.ucla.edu) 
- Zoom (by appointment only): [https://ucla.zoom.us/my/olizardo](https://ucla.zoom.us/my/olizardo)
- Office Hours: **Wednesdays, 1p-3p** 
- Where: 290 Haines Hall

### Introduction
Despite its official title this is not a social network "methods" class. It is a substantive seminar on theory and research in sociology done from a social networks *perspective*. Networks are many things, but in addition to being a suite of methods (which we will cover in the companion course SOCIOL 208A to be offered next year), it is also a way of *thinking* and *theorizing* the social world (sometimes referred to as "formalist" or "structural" analysis), a way of interpreting your data and drawing substantive conclusions from it, and a way of approaching data analysis more generally, even data that were not explicitly collected as "social networks data" (like historical archives, surveys, text data, and other formats). 

Thus, this is class that introduces you to networks thinking across many areas of sociology and the social sciences more generally. A lot of the readings that we will be doing will use some form of network-analytic-techniques (thus, having a background in formal network analysis is a plus), but understanding the nitty-gritty of the methodological approaches of the many articles is not a requirement. The focus here will be on the substantive contribution and the conceptual link to core issues in the discipline not on the methods per se. Although I will touch on methodological issues as we move along. That said, as you will soon find out, network thinking is distinctive precisely because it uses "methods" (e.g., mathematical formalization) as a platform to theorize new concepts. Network thinking is thus a branch of *mathematical sociology* a field that uses mathematical *ideas* to specify sociological *concepts* [@marsden_laumann84; @freeman84]. 

# Requirements
There are two main requirements in the class. Participation and contributions made during our seminar meetings, and a course paper due at the end of the quarter. 

## Participation (50% of grade)

### Weekly Analytic Memo 
The formal side of participation will come in the form of you submitting a short memo (500 to 1000 words) where you try to put two or more of the readings for that week in conversation with one another. The first memo will be due **starting on week 2**. 

Memo specifications:

- **You should pick at least one reading from the Tuesday meeting and at least one reading from the Thursday meeting** as the focus of your memo.
- In your memo you should feel free to raise questions or issues the readings brought up for you as well as any questions, problems, or weaknesses you identify in the argument or the analyses. 
- You may also feel free to connect the readings to other work you are familiar with, pointing to key points of commonality and difference. *The main point of the memo is for me to see evidence of you thinking thought the material, as well as providing fodder for discussion during our meeting*. 
- The memo will be due *by 5p the day before our first class meeting of the week* (that's **Monday**) so that I have a chance to read it and comment on it. You will submit it via the assignments tool on Canvas.

### Class Attendance 
*Attendance is required not optional*. If you need to miss a class meeting please let me know before hand. It is part of your professional socialization to commit to attending class meetings and to inform me when that's not possible (if only as a point of courtesy). 

### Class Discussion 
The informal part of participation will be gauged by your contribution to our class discussion. You can use the thoughts developed in your analytic memo as a take-off point for framing your contribution.  

## Paper (50% of grade)
The basic goal here is for you to end up with something that could be useful to you at the end of the day. As such, I'll give you a set of options here, but if you none of these work, we can talk about something that can be customized for your needs and goals. So by the end of the course you will submit one of the following:

1. **Draft of a research paper**.- This will be a 3500 to 9000 word (double-spaced, Times New Roman Font, 12pt, 1in margins) draft of a research paper. This paper will *contain some kind of data analysis, involving networks broadly defined*. It will include an introduction reviewing literature and setting up a research problem or question. It will then move on to a methods section describing your data and analytic approach, and will close with a discussion section summarizing key findings, outlining implications for substantive research and theory, and describing potential future work and extensions. The goal here is to come up with a draft of a paper that could one day be submitted to the various social science and sociology-oriented journal focused on substantive research, whether "generalist" (e.g., *American Sociological Review*) or "specialist" (e.g., *Social Networks*).

2. **Draft of a Conceptual Paper**.-  This will be a 5000 to 10000 word page (double-spaced, Times New Roman Font, 12pt, 1in margins) draft of a research paper. The paper will focus on a set of concepts, theoretical ideas, or overall perspectives for approaching the study of social life that are *based, inspired, extend, or incorporate network ideas, network thinking, or network concepts and techniques* (broadly defined). The goal here is to come up with a draft of a paper that could one day be submitted to the various social science and sociology-oriented journal focused on "theory." 

3. **Extended Literature Review Draft**.-  This will be a 10-15 page (double-spaced, Times New Roman Font, 12pt, 1in Margins) draft of a literature review of work *done from a social network perspective* on a topic of your interest. The paper will cover what has been done in the field so far, what the strengths and limitations of previous is, and will note gaps or opportunities for future work addressing those limitations or extending the literature to new substantive domains, perhaps linking previous work to the some of the stuff we will be reading in class. 

4. **Draft of a Research Proposal**.- This will be a 10 page (single-spaced, Times New Roman Font, 12pt, 1in margins, including references) draft of a research proposal for a *project incorporating either network thinking, theories, or techniques* that you plan to start in the near future. The proposal will include a background section reviewing previous work, noting their strengths and limitations, and pointing to gaps in the literature. It will also include an "approach" section describing your research project, your main research questions, the data gathering procedures you will use, and the data-analytic techniques you plan to implement once your data is collected. It will close with an implication sections describing what the contributions of your project will be and why it is relevant and important. 

5. **Data Analysis Exercise**.- This will be a 2500 to 5000 word (single-spaced, Times New Roman Font, 12pt, 1in margins) write-up of a data analysis, including some type of network data and/or some kind of network analytic technique (to be discussed and cleared by me). The data source can be obtained from a public repository of network data, or it could be network data that you already have access to or collected yourself. In the paper, you will describe the data, provide key network metrics, describe the data-analytic approach that you will use, and provide a summary of the key empirical patterns that you found, along with a brief conclusion. The paper should be written in the style of a "research note" focused on key empirical findings (not long theory windup or literature review).

Whatever you decide, you will submit *an extended abstract of your final project*, **due on Friday of week 6**. This will be a *one-page, single-spaced* document with 12pt Times New Roman Font and 1in margins.