---
title: "SOCIOL 208B Reading Schedule (Spring 2022)"
format: 
  html:
    page-layout: full
---

## Week 1: Networks As Theory and Perspective

### Tue., Mar. 29
- Marsden, P. V., & Laumann, E. O. (1984). Mathematical Ideas In Social Structural Analysis. *Journal of Mathematical Sociology*, 10(3-4), 271-294. [pdf](https://drive.google.com/file/d/0B8t2mOdAUdzua3lkYndIcHlzcUU/view?usp=sharing&resourcekey=0-5Ly5qYThurHUmNeoOE7D2Q)
- Wellman, B. (1988). Structural Analysis: From Method and Metaphor To Theory and Substance. In B. Wellman & S. D. Berkowitz (Eds.), *Social Structures: A Network Approach*. (Pp. 19–61). Cambridge University Press. [pdf](https://drive.google.com/file/d/0B8t2mOdAUdzuN0FiOGxvT19IakU/view?usp=sharing)
- Emirbayer, M. (1997). Manifesto For A Relational Sociology. *American Journal of Sociology*, 103(2), 281–317. [pdf](https://drive.google.com/file/d/1Oxa0-oSjfqwhlPInsJAUDu3v_i1mW_Zg/view?usp=sharing)

### Thu., Mar. 31
- Erikson, E. (2013). Formalist and Relationalist Theory In Social Network Analysis. *Sociological Theory*, 31(3), 219–242. [pdf](https://drive.google.com/file/d/1Ox8t7O5hhM4CMS_mnn5s7U1NtlS7MVum/view?usp=sharing)
- Emirbayer, M., & Goodwin, J. (1994). Network Analysis, Culture, and The Problem of Agency. *American Journal of Sociology*, 99(6), 1411–1454. [pdf](https://drive.google.com/file/d/145nv4SC_W-kR3zrv4KJlvG7KAUj2pqff/view?usp=sharing)
- Mische, A. (2011). Relational Sociology, Culture, and Agency. In J. Scott & P. J. Carrington (Eds.), *The Sage Handbook of Social Network Analysis* (Pp. 80–97). Sage. [pdf](https://drive.google.com/file/d/13tjWjIeOm6tWeOoAhGh3AhQ5_XLC8z8J/view?usp=sharing)

## Week 2: The Greatest Hits    
### Tue., Apr. 5  
- White, H. C., Boorman, S. A., & Breiger, R. L. (1976). Social Structure From Multiple Networks. I. Blockmodels of Roles and Positions. *American Journal of Sociology*, 81(4), 730–780. [pdf](https://drive.google.com/file/d/1484N_xvWDOJKzMf1-lXRQDW6BXoZ7t-k/view?usp=sharing)
- Breiger, R. L. (1974). The Duality of Persons and Groups. *Social Forces*, 53(2), 181–190. [pdf](https://drive.google.com/file/d/14RVpkcLjmmHabIsLfdn6OjXb9F8FfsIW/view?usp=sharing)
- Freeman, L. C. (1978). Centrality in social networks conceptual clarification. *Social networks*, 1(3), 215-239. [pdf]

### Thu., Apr. 7   
- Granovetter, M. S. (1973). The Strength of Weak Ties. *American Journal of Sociology*, 78(3), 1360–1380. [pdf](https://drive.google.com/file/d/14HkHhCgbE-wN1_E24g3RZlw8O7rkBuv5/view?usp=sharing)
- Centola, D., & Macy, M. (2007). Complex Contagions and the Weakness of Long Ties. *American Journal of Sociology*, 113(3), 702-734. [pdf](https://drive.google.com/file/d/1kkReb-FbonbpUhAya-LzPPp59A-hbJ5A/view?usp=sharing)
- McPherson, M., Smith-Lovin, L., & Cook, J. M. (2001). Birds of a feather: Homophily in social networks. *Annual Review of Sociology*, 27(1), 415-444. [pdf](https://drive.google.com/file/d/1QTJ59HPphngobOwel9iCXu2Lz0GpuMgu/view?usp=sharing)


## Week 3: Brokerage and Intermediation
### Tue., Apr. 12  
- Gould, R. V., & Fernandez, R. M. (1989). Structures of Mediation: A Formal Approach To Brokerage In Transaction Networks. *Sociological Methodology*, 89-126. [pdf](https://drive.google.com/file/d/14Zj3TRMWA9fhPbjVA74h1VBjZDHYB4-I/view?usp=sharing)
- Obstfeld, D., Borgatti, S.P. and Davis, J. (2014). Brokerage As a Process: Decoupling Third Party Action From Social Network Structure. *Research In The Sociology of Organizations*, 40), 135-159. [pdf](https://drive.google.com/file/d/18McIJzahcCr8nYwHfnmE9rOGF7ClLxKm/view?usp=sharing)
- Stovel, K., & Shaw, L. (2012). Brokerage. *Annual Review of Sociology*, 38, 139-158. [pdf](https://drive.google.com/file/d/1P6ssBvZzuZ9ExLEanmaZxFyDom9RtfN7/view?usp=sharing)

### Thu., Apr. 14  
- Burt, R. S. (2004). Structural Holes and Good Ideas. *American Journal of Sociology*, 110(2), 349-399.[pdf](https://drive.google.com/file/d/14f22o9RzAZzZE98Tkjs8iUBNUoMzOc0c/view?usp=sharing)
- Goldberg, A., Srivastava, S. B., Manian, V. G., Monroe, W., & Potts, C. (2016). Fitting In Or Standing Out? The Tradeoffs of Structural and Cultural Embeddedness. *American Sociological Review*, 81(6), 1190-1222. [pdf](https://drive.google.com/file/d/14jP9TJNnDfowl5nLALg1Ys_qsIIh4XI0/view?usp=sharing)
- Aral, S., & Van Alstyne, M. (2011). The diversity-bandwidth trade-off. *American Journal of Sociology*, 117(1), 90-171. [pdf](https://drive.google.com/file/d/1OsBNeInIRMGWkpORio98b_7gViXhMOlL/view?usp=sharing)

## Week 4: Networks In Science
### Tue., Apr. 19 
- Moody, J. (2004). The Structure of A Social Scientific Collaboration Network. *American Sociological Review*, 69, 213-238. [pdf](https://drive.google.com/file/d/14jf9HLcl1t-IJF4Xr8V8WSGgBJBgjP5E/view?usp=sharing)
- Shwed, U., & Bearman, P. S. (2010). The Temporal Structure of Scientific Consensus Formation. *American Sociological Review*, 75(6), 817-840. [pdf](https://drive.google.com/file/d/14kvpeRaTaF1WFZ8rFI6CIpa8JrBNaHDJ/view?usp=sharing)
- Moody, J., & Light, R. (2006). A view from above: The evolving sociological landscape. *The American Sociologist*, 37(2), 67-86. [pdf]

### Thu., Apr. 21  
- Foster, J. G., Rzhetsky, A., & Evans, J. A. (2015). Tradition and Innovation In Scientists’ Research Strategies. *American Sociological Review*, 80(5), 875-908. [pdf](https://drive.google.com/file/d/14laa-VeYisqfD1LIIk8MvmqEt_SaTGjc/view?usp=sharing)
- Mcmahan, P., & Mcfarland, D. A. (2021). Creative Destruction: The Structural Consequences of Scientific Curation. *American Sociological Review*, 86(2), 341-376. [pdf](https://drive.google.com/file/d/14m4aoYvc8NJ1mIxbHvR1G7lRLakL7IKx/view?usp=sharing)

## Week 5: Collaboration, Creativity, and Field Dynamics
### Tue., Apr. 26 
- Vedres, B., & Stark, D. (2010). Structural Folds: Generative Disruption In Overlapping Groups. *American Journal of Sociology*, 115(4), 1150-1190. [pdf](https://drive.google.com/file/d/14rJkKkKUy_ZV73fnFKjoXJQJpn4yj-d7/view?usp=sharing)
- Uzzi, B, & Spiro, J. (2005). Collaboration and Creativity: The Small World Problem. *American Journal of Sociology*, 111, 447-504. [pdf](https://drive.google.com/file/d/14nV4hD6YAt6_YPRaDTcXDuYFFrjsIJdG/view?usp=sharing)

### Thu., Apr. 28  
- Powell, W. W., White, D. R., Koput, K. W., & Owen-Smith, J. (2005). Network Dynamics and Field Evolution: The Growth of Interorganizational Collaboration In The Life Sciences. *American Journal of Sociology*, 110(4), 1132-1205. [pdf](https://drive.google.com/file/d/14vBsO2R4vgsvnEdivSqCiHLzXK5ZsH92/view?usp=sharing)
- Rossman, G., Esparza, N., & Bonacich, P. (2010). I’d Like To Thank The Academy, Team Spillovers, and Network Centrality. *American Sociological Review*, 75(1), 31-51. [pdf](https://drive.google.com/file/d/14oVqQ5EQ1qWbXR1JTDy1QZAxmuSobXjc/view?usp=sharing)

## Week 6: Networks and Culture and Culture in Networks
### Tue., May. 3  
- Breiger, R. L. (2010). Dualities of culture and structure: Seeing through cultural holes. Pp. 37-47 in *Relationale soziologie*. VS Verlag für Sozialwissenschaften. [pdf](https://drive.google.com/file/d/14viAfNQZXNVDexh8AjLli7qpwxxTlCh5/view?usp=sharing)
- DiMaggio, P. (2014). Cultural Networks. Pp. 286-300 in *The SAGE Handbook of Social Network Analysis*. SAGE Publications Ltd. [pdf](https://drive.google.com/file/d/19NRTQVG_zhG364rZcAEeRythcZq8BbTM/view?usp=sharing)
- Lewis, K., & Kaufman, J. (2018). The Conversion of Cultural Tastes Into Social Network Ties. *American Journal of Sociology*, 123(6), 1684-1742. [pdf](https://drive.google.com/file/d/154xc6WXeqWwAX94j8bkbjvVyAdT3AC3o/view?usp=sharing)

### Thu., May. 5  
- Fuhse, J. A. (2009). The Meaning Structure of Social Networks. *Sociological Theory*, 27(1), 51-73. [pdf](https://drive.google.com/file/d/156sDE-Ap6VvGbkhiay_15FWZ5lU4KBXL/view?usp=sharing)
- Ikegami, E. (2000). A Sociological Theory of Publics: Identity and Culture As Emergent Properties In Networks. *Social Research*, 989-1029. [pdf](https://drive.google.com/file/d/15ELmZJ44Yo-oxZxrjONZ0RO9ZmxWroEY/view?usp=sharing)
- Mützel, S., & Breiger, R. (2021). Duality Beyond Persons and Groups. In  *The Oxford Handbook of Social Networks*. Oxford University Press. [pdf](https://drive.google.com/file/d/1dKX2DpM7rVhCGUswZVkL183fm-cRWttz/view?usp=sharing)

## Week 7: Difussion In Networks
### Tue., May. 10   
- Dellaposta, D., Shi, Y., & Macy, M. (2015) Why Do Liberals Drink Lattes?. *American Journal of Sociology*, 120(5), 1473-1511. [pdf](https://drive.google.com/file/d/15VwTQEeuEwXtW6nnZZnjvLQMrJAfe3Yd/view?usp=sharing)
- Centola, D. (2015). The social origins of networks and diffusion. *American Journal of Sociology*, 120(5), 1295-1338. [pdf](https://drive.google.com/file/d/1OzWqgH4cCQeVKhOydGCuNhrQpTiisWcJ/view?usp=sharing)
- Becker, S. O., Hsiao, Y., Pfaff, S., & Rubin, J. (2020). Multiplex Network Ties and the Spatial Diffusion of Radical Innovations: Martin Luther's Leadership In The Early Reformation. *American Sociological Review*, 85(5), 857-894. [pdf](https://drive.google.com/file/d/15XlqwnY5CWsIkbhP1QJLc2CwK2dQ8UL5/view?usp=sharing)

### Thu., May. 12  
- Goldberg, A., & Stein, S. K. (2018). Beyond Social Contagion: Associative Diffusion and The Emergence of Cultural Variation. *American Sociological Review*, 83(5), 897-932. [pdf](https://drive.google.com/file/d/15XvB-RtI8qB8FbgkbU1j8wj3l91-LzAD/view?usp=sharing)
- Bail, C. A., Brown, T. W., & Mann, M. (2017). Channeling hearts and minds: Advocacy organizations, cognitive-emotional currents, and public conversation. *American Sociological Review*, 82(6), 1188-1213. [pdf](https://drive.google.com/file/d/15YVXUs9n0Ik0bl_FE9BMQBl00uRNtxkA/view?usp=sharing)

## Week 8: Networks In History  
### Tue., May. 17  
- Padgett, J. F., & Ansell, C. K. (1993). Robust Action and the Rise of the Medici, 1400-1434. *American Journal of Sociology*, 98(6), 1259–1319. [pdf](https://drive.google.com/file/d/15ZbzATI7_0lUT6IXSwylZn6IiolVkSa7/view?usp=sharing)
- Gould, R. V. (1991). Multiple Networks and Mobilization In The Paris Commune, 1871. *American Sociological Review*, 56(6), 716-729. [pdf](https://drive.google.com/file/d/15gagwyHAFNDOqvO85aSuJMs_FtrvYRxO/view?usp=sharing)
- Erikson, E., & Feltham, E. (2021). Historical Network Research. In *The Oxford Handbook of Social Networks*. Oxford University Press. [pdf](https://drive.google.com/file/d/1OgKxJkj8YKLSrm2VNjcJhGqnCWDJPas0/view?usp=sharing)

### Thu., May. 19  
- Erikson, E., & Bearman, P. (2006). Malfeasance and the Foundations For Global Trade: The Structure of English Trade In The East Indies, 1601–1833. *American Journal of Sociology*, 112(1), 195-230. [pdf](https://drive.google.com/file/d/15hlqs5CZNpiDJXvCkguw2SAjoH9CeheL/view?usp=sharing)
- Bearman, P., Faris, R., & Moody, J. (1999). Blocking The Future: New Solutions For Old Problems In Historical Social Science. *Social Science History*, 23(4), 501-533. [pdf](https://drive.google.com/file/d/15r505mwTMIt80HEXkvGSK3_bLrP9UCFx/view?usp=sharing)

## Week 9: Networks and Inequality
### Tue., May. 24  
- Gould, R. V. (2002). The Origins of Status Hierarchies: A Formal Theory and Empirical Test. *American Journal of Sociology*, 107(5), 1143-1178. [pdf](https://drive.google.com/file/d/15sK2UbyJ9BIWHhynadLZWlw7Yn1FrP_d/view?usp=sharing)
- Gondal, N. (2015). Inequality preservation through uneven diffusion of Cultural materials across stratified groups. *Social Forces*, 93(3), 1109-1137. [pdf](https://drive.google.com/file/d/16btFQcEeOmBaxIGhQTZX-8RmBYNl3rJO/view?usp=sharing)
- Thomas, R. J., & Mark, N. P. (2013). Population size, network density, and the emergence of inherited inequality. *Social Forces*, 92(2), 521-544. [pdf](https://drive.google.com/file/d/15tMy76f6Hhdo1s6yEcTAErAYaKDALAHd/view?usp=sharing)

### Thu., May. 26  
- Burris, V. (2004). The Academic Caste System: Prestige Hierarchies In PhD Exchange Networks. *American Sociological Review*, 69, 239-264. [pdf](https://drive.google.com/file/d/16EQKiVN-K8QAT4hSY8xcT-WUFUvjxWih/view?usp=sharing)
- Fowler, J. H., Grofman, B., & Masuoka, N. (2007). Social networks in political science: Hiring and placement of Ph.Ds, 1960–2002. *PS: Political Science & Politics*, 40(4), 729-739. [pdf](https://drive.google.com/file/d/163s0IvUfQD7CgylX7gN9P5j_jDae8zUB/view?usp=sharing)
- Clauset, A., Arbesman, S., & Larremore, D. B. (2015). Systematic inequality and hierarchy in faculty hiring networks. *Science Advances*, 1(1), e1400005. [pdf](https://drive.google.com/file/d/164Wuf64CREx-NhO2DrhYwsWs0DEmXjXL/view?usp=sharing)
- Gondal, N. (2018). Duality of departmental specializations and PhD exchange: A Weberian analysis of status in interaction using multilevel exponential random graph models (mERGM). *Social Networks*, 55, 202-212. [pdf](https://drive.google.com/file/d/161E-v6W_9UTasHIPELo5xxs6ajQBUAA8/view?usp=sharing)


## Week 10: Networks and The Micro/Macro Link
### Tue., May. 31  
- Mcfarland, D. A., Moody, J., Diehl, D., Smith, J. A., & Thomas, R. J. (2014). Network Ecology and Adolescent Social Structure. *American Sociological Review*, 79(6), 1088-1121. [pdf](https://drive.google.com/file/d/16KdcOamgxA7PBcOtqE7LCzxlaCuszPae/view?usp=sharing)
- Bearman, P. S., Moody, J., & Stovel, K. (2004). Chains of Affection: The Structure of Adolescent Romantic and Sexual Networks. *American Journal of Sociology*, 110(1), 44-91. [pdf](https://drive.google.com/file/d/16Kic-xF2gMfrHqCnfxr2AWnE9oLhCfGb/view?usp=sharing)

### Thu., Jun. 2 
- Levy, B. L., Phillips, N. E., & Sampson, R. J. (2020). Triple Disadvantage: Neighborhood Networks of Everyday Urban Mobility and Violence In US Cities. *American Sociological Review*, 85(6), 925-956. [pdf](https://drive.google.com/file/d/16S5pFjJl_Wot4MSKMjnVpGBsGz1-fZnW/view?usp=sharing)
- Papachristos, A. V. (2009). Murder By Structure: Dominance Relations and the Social Structure of Gang Homicide. *American Journal of Sociology*, 115(1), 74-128. [pdf](https://drive.google.com/file/d/16ToT20IN3KfnzqgL19foS_GZ_jbGobv6/view?usp=sharing)