---
title: "SOCIOL 204 (Sociological Theorizing)"
subtitle: "Spring 2025 Reading Schedule"
format: 
  html:
    page-layout: full
---

## Theory and Theorizing
### Week 0 (Mar. 26)
- Abend, G. (2008). The meaning of 'Theory.' *Sociological Theory*, 26(2), 173-199. 
- Craib, I. (1992) Cutting a Path Through the Jungle. Modern Social Theory. St Martin's Press. (Pp. 15-31).
- Davis, M. S. (1971). That's interesting! Towards a phenomenology of sociology and a sociology of phenomenology. *Philosophy of the Social Sciences*, 1(2), 309-344. 
- Joas, H., & Knöbl, W. (2009). What is Theory? Pp. 1-19 in *Social Theory: Twenty Introductory Lectures*. Cambridge University Press 
- Martin, J. L. (2015) On Theory in Sociology. Pp. 1-44 in *Thinking Through Theory*. W. W. Norton

## Habit and Practice 
### Week 1 (Apr. 2)
- Dubrule, A. (2022). Gender and Habit: John Dewey and Iris Marion Young on Embodiment and Transformation. *The Pluralist*, 17(1), 45-51. 
- Engman, A., & Cranford, C. (2016). Habit and the Body: Lessons for Social Theories of Habit from the Experiences of People with Physical Disabilities. *Sociological Theory*, 34(1), 27-44.
- Lau, R. W. (2004). Habitus and the Practical Logic of Practice An Interpretation. *Sociology*, 38(2), 369-387
- Liao, S. Y., & Huebner, B. (2021). Oppressive things. *Philosophy and Phenomenological Research*, 103(1), 92-113. 
- Ngo, H. (2016). Racist habits: A phenomenological analysis of racism and the habitual body. *Philosophy & Social Criticism*, 42(9), 847-872. 

### Week 2 (Apr. 9)
- Haslanger, S. (2018). What is a social practice? *Royal Institute of Philosophy Supplements*, 82, 231-247. 
- Gold, T. (2022). Contentious Tactics as Jazz Performances: A Pragmatist Approach to the Study of Repertoire Change. *Sociological Theory*, 40(3), 249-271. 
- Pagis, M. (2010). From abstract concepts to experiential knowledge: Embodying enlightenment in a meditation center. *Qualitative Sociology*, 33(4), 469-489. 
- Sullivan, S. (2000). Reconfiguring gender with John Dewey: Habit, bodies, and cultural change. *Hypatia*, 15(1), 23-42. 
- Winchester, D. (2008). Embodying the faith: Religious practice and the making of a Muslim moral habitus. *Social Forces*, 86(4), 1753-1780. 

## Fields, Ecologies, and Institutions

### Week 3 (Apr. 16)

### Week 4 (Apr. 23)

## Interactionism and Phenomenology

### Week 5 (Apr. 30)

### Week 6 (May. 7)

## Networks, Relations, and Structures

### Week 7 (May. 14)

### Week 8 (May. 21)

## Culture, Cognition, and Action

### Week 9 (May. 28)

### Week 10 (Jun. 4)

