---
title: "Repertoire of taste by social class in van den Haak & Wilterdink (2019)"
description: "Post using Correspondence Analysis to visualize the connection between taste repertoire and social class in a published interview study."
author: "Omar Lizardo"
date: "2023-06-22"
categories: [Sociology of taste, Correspondence Analysis]
draft: true
---


```{r Setup, include=FALSE}
     knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
     library(conflicted)
     library(FactoMineR)
     library(kableExtra)
     library(sjPlot)
     library(tidyverse)
     library(wesanderson)
```

```{r Data Table}
     dat <- matrix(c(2, 5, 1, 6, 3, 13, 22, 20, 13, 0, 2, 3), 
                   nrow = 4, byrow = TRUE)
     rownames(dat) <- c("Only hierarchical", "Only egalitarian", 
             "Both: ambivalent", "Neither: neutral")
     colnames(dat) <- c("Stayers (Educated)", "Movers (Low Educ to High Educ)", "Stayers (Less Educ.)")
```

```{r CA}
     ca.res <- CA(dat, graph = FALSE)
     plot.dat <- bind_rows(data.frame(ca.res$row$coord), 
                           data.frame(ca.res$col$coord)) %>% 
               cbind(item = factor(c(1, 1, 1, 1, 2, 2, 2)))
```

```{r Table}
        
    kbl(dat, format = "html", align = "c", padding = 2) %>% 
        kable_styling(bootstrap_options = c("hover", "condensed", "responsive"))
```


```{r Plot}
     n <- rownames(plot.dat)
     d1p <- paste(as.character(round(ca.res$eig[1, 2])), "%", sep = "")
     d2p <- paste(as.character(round(ca.res$eig[2, 2])), "%", sep = "")

     p <- ggplot(data = plot.dat, aes(x = Dim.1, y = Dim.2, fill = item))
     p <- p + geom_vline(xintercept = 0, color = "gray40")
     p <- p + geom_hline(yintercept = 0, color = "gray40")
     p <- p + geom_label(aes(label = n), color = "white", size = 4)
     p <- p + scale_y_continuous(limits = c(-.5, .75))
     p <- p + scale_x_continuous(limits = c(-1, 1))
     p <- p + scale_fill_manual(values = wes_palettes$Cavalcanti1[c(2, 5)])
     p <- p + labs(x = paste("First Dimension:", d1p), 
                   y = paste("Second Dimension:", d2p))
     p <- p + guides(fill = "none")
     p <- p + theme_sjplot2()
```

# Introduction
In summarizing their results, van den Haak and Wilterdink note that "[a]s Table 1 specifies, the well-educated are clearly overrepresented in the hierarchical type and the (much larger) category of the ambivalent type, whereas the less-educated make up larger pro-portions of the egalitarian and the neutral categories (p. 422)."

```{r, fig.cap = "Correspondence Analysis Plot of Data in Table 1 of van den Haak & Wilterdink (2019)"}
   p
```

